version: "3.1"

services:

  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: passwd
      POSTGRES_DB: weather_station
    ports: 
      - "5432:5432"
  
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
